### PR TITLE
Accepts zIndex=0 prop

### LINKED ISSUE #16: Prop `zIndex` should accept the number 0 as a value
There's an issue with the `zIndex` prop, which is set to `1` when the container sets its value to `0`.

### PR DESCRIPTION
**Pull request by claudiopro**
Uses `Number.isFinite()` instead of the `||` operator to check if the value of the `zIndex` prop is set,  fixes #16.

### CODE REVIEW

**Comment by kdeloach** [comment]
Thanks for the contribution! Could you revert the `dist/*` files from this commit? I usually rebuild these files when I push a release.

**Comment by claudiopro** [comment]
Sure thing, will do it right away. Thanks for considering this PR 😃

**Comment by kdeloach** [comment]
I pushed this change in 3.1.1. Thanks again.

**Comment by claudiopro** [comment]
Super, thank you!

**Pull request merged**
